garageSize: 10
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM
    include-exception: true